service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  hasOpenAPI: "true"
eksCluster: false
replicaCount: 2
image:
  repository: coco/internal-concordances
  pullPolicy: Always
resources:
  limits:
    memory: 32Mi
  requests:
    memory: 16Mi
